"""add_calculator_history

Revision ID: 7c7360efca3c
Revises: f7b8e5400ef5
Create Date: 2026-04-30 19:44:01.902512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c7360efca3c'
down_revision: Union[str, None] = 'f7b8e5400ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculator_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expression', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculator_history_id'), 'calculator_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calculator_history_id'), table_name='calculator_history')
    op.drop_table('calculator_history')
    # ### end Alembic commands ###
