"""initial_schema

Revision ID: ca6d079693fc
Revises: 
Create Date: 2026-04-29 18:42:23.007792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6d079693fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brick_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_number', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('location_tag', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_number')
    )
    op.create_index(op.f('ix_brick_teams_id'), 'brick_teams', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('employee_category', sa.String(), nullable=False),
    sa.Column('pay_frequency', sa.String(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('religion', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('boss_contractor_name', sa.String(), nullable=True),
    sa.Column('home_city', sa.String(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('fuel_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liters_bought', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('liters_remaining', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('station_name', sa.String(), nullable=False),
    sa.Column('purchaser_name', sa.String(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('receipt_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_stocks_id'), 'fuel_stocks', ['id'], unique=False)
    op.create_table('fuel_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_name', sa.String(), nullable=False),
    sa.Column('liters_used', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('given_by', sa.String(), nullable=False),
    sa.Column('usage_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logged_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_usages_id'), 'fuel_usages', ['id'], unique=False)
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_mode', sa.Enum('trawli', 'custom', name='ordermode'), nullable=False),
    sa.Column('brick_category', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_mobile', sa.String(), nullable=False),
    sa.Column('customer_address', sa.Text(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('lead_source', sa.String(), nullable=True),
    sa.Column('salesperson', sa.String(), nullable=True),
    sa.Column('total_qty', sa.Integer(), nullable=False),
    sa.Column('price_per_trawli', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('dispatched_qty', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Completed', 'Cancelled', 'Force_Closed', name='orderstatus'), nullable=True),
    sa.Column('close_reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_orders_id'), 'sales_orders', ['id'], unique=False)
    op.create_table('daily_productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('bricks_count', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('logged_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['brick_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_productions_id'), 'daily_productions', ['id'], unique=False)
    op.create_table('dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(), nullable=False),
    sa.Column('qty_dispatched', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatches_id'), 'dispatches', ['id'], unique=False)
    op.create_table('extra_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_logged', sa.Date(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extra_works_id'), 'extra_works', ['id'], unique=False)
    op.create_table('order_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('received_by', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_payments_id'), 'order_payments', ['id'], unique=False)
    op.create_table('payroll_ledgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('SALARY', 'CLEAR_DUES', 'ADVANCE_GIVEN', name='payrolltransactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('due_created', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('advance_deducted', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_ledgers_id'), 'payroll_ledgers', ['id'], unique=False)
    op.create_table('salary_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('old_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('new_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('old_pay_type', sa.String(), nullable=False),
    sa.Column('new_pay_type', sa.String(), nullable=False),
    sa.Column('change_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_histories_id'), 'salary_histories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_histories_id'), table_name='salary_histories')
    op.drop_table('salary_histories')
    op.drop_index(op.f('ix_payroll_ledgers_id'), table_name='payroll_ledgers')
    op.drop_table('payroll_ledgers')
    op.drop_index(op.f('ix_order_payments_id'), table_name='order_payments')
    op.drop_table('order_payments')
    op.drop_index(op.f('ix_extra_works_id'), table_name='extra_works')
    op.drop_table('extra_works')
    op.drop_index(op.f('ix_dispatches_id'), table_name='dispatches')
    op.drop_table('dispatches')
    op.drop_index(op.f('ix_daily_productions_id'), table_name='daily_productions')
    op.drop_table('daily_productions')
    op.drop_index(op.f('ix_sales_orders_id'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_fuel_usages_id'), table_name='fuel_usages')
    op.drop_table('fuel_usages')
    op.drop_index(op.f('ix_fuel_stocks_id'), table_name='fuel_stocks')
    op.drop_table('fuel_stocks')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_brick_teams_id'), table_name='brick_teams')
    op.drop_table('brick_teams')
    # ### end Alembic commands ###
